# CodeRabbit Configuration
language: en-US  # Language for reviews

# Review settings
reviews:
  profile: chill  # Options: chill, assertive
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  auto_title_placeholder: '@coderabbitai'
  changed_files_summary: true
  sequence_diagrams: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  suggested_reviewers: true
  poem: true
  
  # Path filters and instructions
  path_filters: []  # Add glob patterns to include/exclude files
  path_instructions: []  # Add path-specific review instructions
  
  # Auto review settings
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    
  # Tool integrations
  tools:
    # Common tools (all enabled by default)
    ast-grep:
      essential_rules: true
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    biome:
      enabled: true
    eslint:
      enabled: true
    gitleaks:
      enabled: true

# Chat settings
chat:
  auto_reply: true
  create_issues: true

# Knowledge base settings
knowledge_base:
  web_search:
    enabled: true
  learnings:
    scope: auto
  issues:
    scope: auto
  pull_requests:
    scope: auto

# Code generation settings
code_generation:
  docstrings:
    path_instructions:
      - path: "**/*.js"
        instructions: |
          End all docstrings with a notice that says "Auto-generated by CodeRabbit.".
          Do not omit the closing tags; the docstring must be valid.